services:
  openwhisk:
    image: openwhisk/standalone:nightly
    container_name: ow-standalone
    user: "0:0"
    network_mode: "bridge"
    ports:
      - "3233:3233"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - whisk_data:/root/.openwhisk/standalone/server-3233
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_API_VERSION=1.44
      # OW is now on 172.17.x.x, action containers also 172.17.x.x
      # So OW can reach action containers on 172.17.x.x:8080
      # api_host = 172.17.0.1 (bridge gateway, accessible from bridge containers)
      - CONFIG_whisk_api_host_name=172.17.0.1
      - CONFIG_whisk_api_host_port=3233
      - CONFIG_whisk_api_host_proto=http

volumes:
  whisk_data: